n=input('Digite algo')
print(n, type(n))
print('{} é númerico?'.format(n),n.isnumeric())
print('{} é alfanumérico?'.format(n),n.isalnum())
print('{} é digit?'.format(n),n.isdigit())
print('{} é todo em minuscúlo?'.format(n),n.islower())
print('{} é todo em maiuscúlo?'.format(n),n.isupper())
print('{} é imrpimível?'.format(n),n.isprintable())
print('{} está capitalizada?'.format(n),n.istitle())
print('{} Só tem espaço?'.format(n),n.isspace())